class Beaches
  LIST = [
    { beach_slug: "praia-de-carcavelos", cam_slug: "praia-de-carcavelos" },
    { beach_slug: "praia-de-matosinhos", cam_slug: "praia-de-matosinhos" },
    { beach_slug: "praia-da-baia", cam_slug: "praia-de-espinho" },
    { beach_slug: "praia-grande", cam_slug: "praia-grande" },
    { beach_slug: "praia-de-supertubos", cam_slug: "peniche-supertubos" },
    { beach_slug: "praia-do-guincho", cam_slug: "praia-do-guincho" },
    { beach_slug: "praia-de-supertubos", cam_slug: "peniche-supertubos" },
    { beach_slug: "praia-do-guincho", cam_slug: "praia-do-guincho" },
    { beach_slug: "praia-do-guincho", cam_slug: "praia-do-guincho" },
    { beach_slug: "praia-do-lagide", cam_slug: "lagide-e-baia" },
    { beach_slug: "praia-do-mar-foz-do-arelho", cam_slug: "foz-do-arelho" },
    { beach_slug: "praia-do-norte", cam_slug: "praia-do-norte" },
    { beach_slug: "praia-de-ribeira-dilhas", cam_slug: "ribeira-dilhas" },
    { beach_slug: "praia-de-leca-da-palmeira", cam_slug: "leca-da-palmeira" },
    { beach_slug: "praia-do-cabedelo", cam_slug: "figueira-da-foz-cabedelo" },
    { beach_slug: "praia-da-foz-do-lizandro", cam_slug: "foz-do-lizandro" },
    { beach_slug: "praia-de-sao-torpes", cam_slug: "praia-de-sao-torpes" },
    { beach_slug: "praia-da-torre", cam_slug: "praia-da-torre" },
    { beach_slug: "praia-da-costa-nova", cam_slug: "costa-nova" },
    { beach_slug: "praia-da-foz-dos-ouricos", cam_slug: "figueira-da-foz-cabedelo-buarcos" },
    { beach_slug: "praia-do-guincho", cam_slug: "praia-do-guincho-norte" },
    { beach_slug: "praia-de-odeceixe", cam_slug: "odeceixe" },
    { beach_slug: "praia-da-consolacao", cam_slug: "praia-da-consolacao" },
    { beach_slug: "praia-da-cresmina", cam_slug: "cresmina" },
    { beach_slug: "praia-do-carvalhal", cam_slug: "praia-do-carvalhal" },
    { beach_slug: "praia-de-sao-juliao", cam_slug: "sao-juliao" },
    { beach_slug: "praia-de-buarcos", cam_slug: "paco-de-arcos" },
    { beach_slug: "praia-de-sao-lourenco", cam_slug: "ericeira-sao-lourenco" },
    { beach_slug: "praia-do-castelejo", cam_slug: "viana-do-castelo-cabedelo" },
    { beach_slug: "praia-da-zambujeira-do-mar", cam_slug: "zambujeira-do-mar" },
    { beach_slug: "praia-de-almograve", cam_slug: "almograve" },
    { beach_slug: "praia-pequena", cam_slug: "praia-pequena" },
    { beach_slug: "praia-da-arda", cam_slug: "ericeira-praia-da-calada" },
    { beach_slug: "praia-da-bafureira", cam_slug: "bafureira" },
    { beach_slug: "praia-do-baleal", cam_slug: "peniche-baleal-panoramica" },
    { beach_slug: "praia-de-sao-joao-da-caparica", cam_slug: "costa-de-caparica-sao-joao-cova-do-vapor" },
    { beach_slug: "praia-da-empa-pedra-branca", cam_slug: "ericeira" },
    { beach_slug: "praia-do-cds", cam_slug: "costa-da-caparica-cds" }
  ]
end
